// Integration tests: replay the scapy-generated sample pcaps through the full
// capture -> dissect -> detect pipeline and assert the right alerts fire.
//
// The pcaps live in tests/data and are regenerated by tools/make_sample_pcaps.py.
// PKTSCOPE_DATA_DIR is defined by CMake to point at that directory.
#include <string>
#include <vector>

#include "doctest.h"
#include "pktscope/capture.hpp"
#include "pktscope/detect.hpp"
#include "pktscope/flow.hpp"
#include "pktscope/stats.hpp"

using namespace pktscope;

#ifndef PKTSCOPE_DATA_DIR
#define PKTSCOPE_DATA_DIR "tests/data"
#endif

namespace {
struct Result {
    Stats stats;
    FlowTable flows;
    std::vector<Alert> alerts;
};

Result analyze(const std::string& name) {
    Result r;
    Detector det;
    Capture cap = Capture::offline(std::string(PKTSCOPE_DATA_DIR) + "/" + name);
    cap.run([&](const Packet& p) {
        r.stats.add(p);
        if (!p.malformed) r.flows.update(p);
        det.inspect(p);
    });
    r.alerts = det.all_alerts();
    return r;
}

int count_kind(const std::vector<Alert>& a, const std::string& kind) {
    int n = 0;
    for (const auto& x : a) if (x.kind == kind) ++n;
    return n;
}
}  // namespace

TEST_CASE("benign capture raises no alerts") {
    Result r = analyze("benign.pcap");
    CHECK(r.stats.packets > 0);
    CHECK(r.alerts.empty());
    CHECK(r.stats.malformed == 0);
}

TEST_CASE("port scan pcap is detected") {
    Result r = analyze("port_scan.pcap");
    CHECK(count_kind(r.alerts, "port-scan") >= 1);
    CHECK(r.stats.malformed == 0);
}

TEST_CASE("stealth scan pcap flags NULL/FIN/Xmas") {
    Result r = analyze("stealth_scan.pcap");
    CHECK(count_kind(r.alerts, "stealth-scan") == 5);
}

TEST_CASE("ARP spoofing pcap is detected") {
    Result r = analyze("arp_spoof.pcap");
    CHECK(count_kind(r.alerts, "arp-spoof") >= 1);
}

TEST_CASE("SYN flood pcap is detected") {
    Result r = analyze("syn_flood.pcap");
    CHECK(count_kind(r.alerts, "syn-flood") >= 1);
}

TEST_CASE("DNS tunnel pcap is detected") {
    Result r = analyze("dns_tunnel.pcap");
    CHECK(count_kind(r.alerts, "dns-tunnel") >= 1);
    CHECK(r.stats.dns >= 1);
}
